### ISSUE TITLE
Password Can Be Changed to Empty Password

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#10]
**Severity**: Medium

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: Not sure if this is intentional or not, but applications usually require their users to have some sort of password.

![image](https://user-images.githubusercontent.com/17243618/109086943-80c0d000-76da-11eb-9a6c-1d252f7b02c7.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
