### ISSUE TITLE
No Error Handling for Faulty POST Requests

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#11]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I wanted to see what would happen if I left out a field in the POST request, and it seems there's no error handling in place if I were to do this. I could report this for every API call, but I assume this is a global issue, and not limited solely to ``/forgotpassword``.

![image](https://user-images.githubusercontent.com/17243618/109087114-d72e0e80-76da-11eb-8dde-8b9bddd28a92.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109087147-e7de8480-76da-11eb-83fe-b14a8edb631f.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
