### ISSUE TITLE
Trying to Verify a Blank Code Isn't Handled

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#12]
**Severity**: Medium

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I tried to call ``127.0.0.1:8000/verify/`` to see what would happen, and this was the response:

![image](https://user-images.githubusercontent.com/17243618/109087539-a5697780-76db-11eb-8067-62c503f857f0.png)

The command line seems to have returned the right error:

![image](https://user-images.githubusercontent.com/17243618/109087591-c0d48280-76db-11eb-9ccb-f2d86ced0b87.png)

However, when the front end just receives the HTML as the response (instead of a nice small object that says "ERROR 404"), that's usually indicative that something wasn't handled.

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
This is intended behavior, in debug mode it shows this error. This is intentional in django.
