### ISSUE TITLE
No Error Handling For /getAdminUsers with Faulty Inputs

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#13]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I assume this extends to other requests too, but if I run ``/getAdminUsers/`` with any follow-up argument, I get an unhandled 404 error. There should be something in place to make sure that the request is correct before processing it.

![image](https://user-images.githubusercontent.com/17243618/109087921-67b91e80-76dc-11eb-8042-e659aeee60e2.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
This is intended behavior, in debug mode it shows this error. This is intentional in django.
