### ISSUE TITLE
/createSubCategory Can't Handle Blank Inputs

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#15]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I tried correctly sending a POST request with ``/createSubCategory``, but when trying to create a category with name "" and user_id "", the program crashed:

![image](https://user-images.githubusercontent.com/17243618/109091696-41e34800-76e3-11eb-8e4d-f060d87918f1.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109091745-558eae80-76e3-11eb-8795-3417fa51554a.png)
![image](https://user-images.githubusercontent.com/17243618/109091761-5d4e5300-76e3-11eb-99f8-6c3f38732116.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
