### ISSUE TITLE
/getOrder Doesn't Work as Defined

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#18]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: The API documentation says it takes in a parameter ``order_id``, but Python expected just ``id``.

![image](https://user-images.githubusercontent.com/17243618/109092657-f29e1700-76e4-11eb-8cf3-d41236175e11.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109092696-02b5f680-76e5-11eb-9c0a-3848b663b0ec.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Id is the correct parameter, closing as the functionality wasn't there previously. Working now.
