### ISSUE TITLE
/createItem Straight Up Doesn't Work

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#19]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: Python wants a "description" field, while the API says to use a "desc" field.

![image](https://user-images.githubusercontent.com/17243618/109093940-385bdf00-76e7-11eb-9991-c86e8176fccf.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109093963-41e54700-76e7-11eb-9c1f-16706f689995.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
