### ISSUE TITLE
/updateItem Doesn't Work

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#20]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: Seems to be another case of a field being recorded differently in the API vs what Python expects.
The API has the field "desc", while Python is expecting "description".

![image](https://user-images.githubusercontent.com/17243618/109093732-d8fdcf00-76e6-11eb-8d4b-17432905791c.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109093817-fcc11500-76e6-11eb-8aba-fee74cfe6c4e.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
