### ISSUE TITLE
/createItem With "Bug-Fix" Still Doesn't Work

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#21]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I modified the JSON to use "description" instead of "desc" (as written in my previous issues), and now it seems Python doesn't like my subcategory id. Truth be told I had no idea what to put here, but the fact that it's labelled "id" indicates (to me at least) that a number is expected. Instead of just throwing an error for the Id not existing, I get this error:

![image](https://user-images.githubusercontent.com/17243618/109094225-9dafd000-76e7-11eb-9415-ffa7631ce20a.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109094253-a7d1ce80-76e7-11eb-85e0-de97d688d5ac.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
