### ISSUE TITLE
Syntax Error in JSON Object Throws Unhandled Error

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#22]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I accidentally made a typo in one of my JSON objects (below a ``,`` instead of ``:``, and this error showed up:

![image](https://user-images.githubusercontent.com/17243618/109094963-da2ffb80-76e8-11eb-9c41-5eda820bcaab.png)

And the command line output:

![image](https://user-images.githubusercontent.com/17243618/109094982-e5832700-76e8-11eb-9189-3199221e3e08.png)

Seems there's no error handling in place for when a JSON is syntactically incorrect.

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Deferring this responsibility to Aquafina, closing as resolved.
