### ISSUE TITLE
/deleteItem Can Delete Items that Don't Exist

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#23]
**Severity**: Medium

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: Pretty self-explanatory. There probably should be some alternate confirmation in place when an item not in the database is attempted to be deleted. What would happen if there was a mistake on the front-end and they accidentally tried to delete the wrong thing? They'd need to know somehow that they didn't delete the right item.

![image](https://user-images.githubusercontent.com/17243618/109095143-2bd88600-76e9-11eb-9ae0-331354a95938.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
