### ISSUE TITLE
/register should not accept non-string emails

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#25]
Using commit 068df99

/register should do type validation on the email, as well as string

![image](https://user-images.githubusercontent.com/34824500/109362744-a6c0ae80-7859-11eb-8e2d-c522e0562cc8.png)

**Comment by alishahimtiaz** [comment]
Leave it to Django to not include DB level validation... 
https://stackoverflow.com/questions/18368207/django-emailfield-accepts-invalid-values

Fixed, thank you for the note.
