### ISSUE TITLE
models.py _generate_jwt_token method accesses property which does not exist

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#26]
[link to code](https://github.com/Danielwu9226/community-currency-reframery/blob/master/backend/reframery/models.py#L62)

This line of code is referencing a method which does not exist which I think is causing some other bugs here.

I get the following error from pylint:
Module 'jwt' has no 'encode' member

pylint version: 2.6.0
python version: 3.8.5

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
