### ISSUE TITLE
when invalid email passed, /forgotpassword/ should return 400 not 401

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#28]
From [068df99](https://github.com/Danielwu9226/community-currency-reframery/commit/068df999536b9714153b4a9d9cba4cbf9a8320f5)

To reproduce:

1. pick a user that hasn't been created before. I am using "abcd" 
2. run the following
```
curl --location --request POST 'http://localhost:8000/forgotpassword/' \
--header 'Content-Type: text/plain' \
--data-raw '{"email": "abcd", "password":1243}'
```
![image](https://user-images.githubusercontent.com/34824500/109364152-2bacc780-785c-11eb-88d6-9027775278e9.png)

This isn't per se an authentication error but should be a 400 bad request.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
