### ISSUE TITLE
Tokenization for senstive requests

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#30]
When dealing with sensitive data, requests should be authenticated by passing i.e. a token in the header.

I.e. the endpoint /getAdminUsers should not be something that any unauthenticated person can invoke

steps to reproduce:
```
curl --location --request GET 'http://localhost:8000/getAdminUsers'
```
response 
`{"data": [], "http_code": "200"}`

**Comment by alishahimtiaz** [comment]
Added auth levels for people who can call this function.
