### ISSUE TITLE
performing invalid methods on an endpoint should not have 401 unauthorized invalid route

### ISSUE THREAD

**Issue by KristieTom12** [Danielwu9226/community-currency-reframery#32]
Using [version at commit 068df999](https://github.com/Danielwu9226/community-currency-reframery/commit/068df999536b9714153b4a9d9cba4cbf9a8320f5)
Steps to reproduce:

`curl --request GET 'http://localhost:8000/deleteItem'`

Response:
`{"message": "Invalid Route", "http_code": "401 Unauthorized"}`

Instead should say "invalid method" and "400 bad request"

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
