### ISSUE TITLE
'Confirm your Secret Backup Phrase' Animation does not allow you to drag any word to last position

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#33]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Create a new account and with new password 
2. Memorize Backup phrases
3. After confirming go to 'Confirm backup Phrase'
4. select 4 words.
5. Try to drag and drop any  word to the last postion

Observation:
Unable to drag a word to last position
Expected:
Should be able to drag word to last position

**Comment by alishahimtiaz** [comment]
Cannot repro. Closing as resolved.
