### ISSUE TITLE
Inconsistent design on Swap page

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#34]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Create Account
2. Click on Swap on main dashboard
3. Unable to click on top right and go to account or settings (you are able to return back to main dashboard)
 
Observation:
Unable to click on top right and go to account or settings (you are able to return back to main dashboard)
Expected:
Should have consistent behaviour in that should be able to leave swap page for both 'MetaMask' link and 'Account' link or neither. Inconsistent design.

**Comment by CharlesZhang99-zz** [comment]
Metamask is a 3rd party tool. We cannot make changes to it.
