### ISSUE TITLE
Unexpected error on https://faucet.metamask.io/

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#35]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Create Account
2. Switch to test Ropsten network
3. Click on buy
4. Click on Get Ether
5. Click on Request 1 Ether from faucet multiple times
6. If prompted close the prompt window
7. Continue Clicking until erorr shown is displayed

Observation:
![Screenshot from 2021-03-03 18-56-52](https://user-images.githubusercontent.com/35702189/109888887-54fd9700-7c52-11eb-91a8-8db0654b60b5.png)

Unexpected error is presented to user.
Expected:
Should have better user friendlty error presentation inside of error message

**Comment by alishahimtiaz** [comment]
That is a third party library that we do not have control over. Closing this as won't do.
