### ISSUE TITLE
Transaction History does not show Transaction After receiving test Ether

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#36]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Go to https://github.com/Danielwu9226/community-currency-reframery/blob/master/smart-contract-usage.md
2. Follow the instructions and deposit a test Ether to account
3. Click on transaction History

Observation:
Unable to see deposit
Expected:
Should be able to see transaction
![Screenshot from 2021-03-03 19-01-48](https://user-images.githubusercontent.com/35702189/109889371-3ea40b00-7c53-11eb-9960-af4c168f3738.png)

**Comment by CharlesZhang99-zz** [comment]
Metamask is a 3rd party tool.
