### ISSUE TITLE
Unexpected Error when on faucet.metamask.io

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#37]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1.Go to faucet.metamask.io
2. After creating an account click on '1 ether' under user 
3. close the prompt window immediately

Observation:
Error message is displayed to user 
Expected:
Proper error display for user or no error should be displayed since no action was taken
![Screenshot from 2021-03-03 19-10-38](https://user-images.githubusercontent.com/35702189/109889863-2c769c80-7c54-11eb-88d5-84a6713baee3.png)

**Comment by alishahimtiaz** [comment]
Cannot repro. Marking as resolved.

**Comment by CharlesZhang99-zz** [comment]
The free faucet is a 3rd party tool for developers. We cannot make changes to it.
