### ISSUE TITLE
Error when switching networks

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#38]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Go to account main dashboard 
2. click on send 
3. click on top right of network name
4. switch network

Observation:
An error occurs
Expected:
Proper error handling or prevention
![Screenshot from 2021-03-03 19-22-26](https://user-images.githubusercontent.com/35702189/109890908-18cc3580-7c56-11eb-88ce-c8dc4c3a05e5.png)

**Comment by CharlesZhang99-zz** [comment]
Metamask is a popular 3rd party tool. We cannot make changes to it.
