### ISSUE TITLE
Transaction History Does Not Show correct Balance after making TX

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#39]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Go to https://faucet.metamask.io/
2. Donate multiple Eth to user
3. Go back to Account Transaction History

Observation:
Incorrect Balance amount is displayed instead of actual history and balance. 

Expected:
History should match Account balance.
![Screenshot from 2021-03-03 19-32-35](https://user-images.githubusercontent.com/35702189/109891679-7e6cf180-7c57-11eb-996e-e5e5f2b11839.png)

**Comment by CharlesZhang99-zz** [comment]
This is because there is a transaction free involved with each transaction. Metamask is a 3rd party tool.
