### ISSUE TITLE
Unexpected Error when Requesting and Donating Ether to User on faucet.metamask.io

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#40]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Go to faucet.metamask.io
2. Clcik on request and donate ether to users 
3. Make multiple requests from faucet

Observation:
HTML Error appears on screen.
![Screenshot from 2021-03-03 19-20-21](https://user-images.githubusercontent.com/35702189/109891951-0d7a0980-7c58-11eb-9ed1-e1f7adf2f9a5.png)

Expected:
Should have some error handling or prevention to prevent user from seeing this issue.

**Comment by CharlesZhang99-zz** [comment]
The free faucet is a 3rd party tool (used by developers for testing) that we have no control over. Users will not be interacting with a free faucet in our final app.
