### ISSUE TITLE
Error is shown after sending ETH on Ropsten Test Network

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#41]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Go to main dashboard
2. Click on Buy 
3. Click on Get Ether
4. Click on 1 ether
5. Click on Edit
6. Edit ETH amount so it is below account balance and balance is sufficient
7. Click on next
8. Click on confirm

Observation:
After clicking on confirm user is presented with error about insufficient funds. 
Expected:
User should be presented with correct display especially since the TX goes through moments later instead of being told insufficient funds.
![before](https://user-images.githubusercontent.com/35702189/109893063-01db1280-7c59-11eb-9257-d772961ab94e.png)
![after](https://user-images.githubusercontent.com/35702189/109893065-01db1280-7c59-11eb-85d7-d4bb5d92b789.png)

**Comment by CharlesZhang99-zz** [comment]
Our users will only be transacting with DANC tokens, not ether. Metamask is a 3rd party tool that we have no control over.
