### ISSUE TITLE
Speeding up TX causes Crash

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#42]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Create a TX that has the 'speed up' option under 'Activity'
2. Click on Speed up

Observation:
Application Crashes 
Expected:
Proper Error handling or prevention.
![Screenshot from 2021-03-03 19-46-57](https://user-images.githubusercontent.com/35702189/109893318-71e99880-7c59-11eb-8ea9-cfddabf78461.png)

**Comment by CharlesZhang99-zz** [comment]
This is probably an issue with Metamask (3rd party). Not related to our smart contract.
