### ISSUE TITLE
Able to send TX with 0 ETH in balance

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#43]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Create a an account
2. Click on top right of dashboard and Create a new account
3. Switch to new account created
4. Go to faucet.metamask.io
5. Click on 1 ether
6. Click on Edit
7. Make the ETH amount 0
8. Click on Next
9. Click on Confirm
10. TX hash appears on screen

Observation:
Able to make a TX with insufficient funds
Expected:
Should not be able to make a TX with insufficient funds

![Screenshot from 2021-03-03 19-52-43](https://user-images.githubusercontent.com/35702189/109893852-6cd91900-7c5a-11eb-8ca1-f643e2edef6b.png)

**Comment by CharlesZhang99-zz** [comment]
This is because you're requesting ether from the faucet, not sending ether to it. So the amount doesn't matter. Free faucets are also only a test net tool so users will not encounter a faucet in our final app when the smart contract is deployed to the main-net.
