### ISSUE TITLE
Transactions do not save after refreshing page

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#44]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Make a TX on faucet.metamask.io
2. Refresh Page

Observation:
TX disappears after making TX
Expected:
TX should remain there

![before1](https://user-images.githubusercontent.com/35702189/109894110-df49f900-7c5a-11eb-8300-3a5c7fa6af17.png)
![afterRefresh](https://user-images.githubusercontent.com/35702189/109894142-f25cc900-7c5a-11eb-952c-38d487d1bb77.png)

**Comment by CharlesZhang99-zz** [comment]
This is an issue with the free 3rd party faucet which we do not have control over. There will be no free faucet when the smart contract is deployed to the main-net.
