### ISSUE TITLE
Error in registering  new user in backend

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#45]
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

Repro:
1. Run backend Server
2. Make a POST request in POSTMAN to register user

Observation:
JSON response message returns 404 and User alreaady exists.
Expected:
Should return success since new user is being created for first time.
![Screenshot from 2021-03-03 20-25-40](https://user-images.githubusercontent.com/35702189/109896482-f7bc1280-7c5e-11eb-9ce1-d8590d3bef71.png)

**Comment by alishahimtiaz** [comment]
Can not repro. Closing.
