### ISSUE TITLE
Error shown when making /getOrder with faultr

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#46]
Version:
https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn/related?hl=en&pli=1&authuser=2

Repro:
1. Run Server
2. Make a /gerOrder request with faulty ID

Observation:
![Screenshot from 2021-03-03 20-36-37](https://user-images.githubusercontent.com/35702189/109897101-30102080-7c60-11eb-82f5-e23e7c3113bb.png)

Expected:
Proper Error Handling

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
