### ISSUE TITLE
No Error Handling For invalid input on /getItem

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#47]
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

Repro:
1. Run server
2. Make /getItem with "string" as value for key "item_id"

Observation:
![Screenshot from 2021-03-03 20-39-48](https://user-images.githubusercontent.com/35702189/109897528-d9efad00-7c60-11eb-8ade-852351c58952.png)

Expected:
Should have error handling

**Comment by alishahimtiaz** [comment]
Resolved, thank you.
