### ISSUE TITLE
KeyError when calling /updateItem when using API documentation method definition 

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#49]
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

Repro:
1. Run Server
2. Make a PUT request to /updateItem using definition found in https://github.com/Danielwu9226/community-currency-reframery/blob/master/API_DOCS.md

Observation:
![Screenshot from 2021-03-03 20-49-01](https://user-images.githubusercontent.com/35702189/109898410-36070100-7c62-11eb-8bf4-d5e15dac42cd.png)

Expected:

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
