### ISSUE TITLE
/deleteItem expects a number after inputting string as key's value

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#50]
Version:
https://github.com/Danielwu9226/community-currency-reframery/blob/master/README.md

Repro:
1. Run Server
2. Delete an Item with a String as ID for subCategoryID

Run Server
Make a DELETE request to /deleteSubCategory using definition found in https://github.com/Danielwu9226/community-currency-reframery/blob/master/API_DOCS.md

Observation:
![Screenshot from 2021-03-03 20-53-28](https://user-images.githubusercontent.com/35702189/109898734-b62d6680-7c62-11eb-9286-93578bf2663a.png)

Expected:
Since the API Documentation says the param should be of string type, the call should work.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
