### ISSUE TITLE
Error in API Documentation  /deleteItem

### ISSUE THREAD

**Issue by immanuel-odisho** [Danielwu9226/community-currency-reframery#51]
Version:
02ab7fa 9

Issue:
Documentation states that /deleteSubCategory expects subCategoryID to be of type String but the actual backend expects a number.

Observation:
![Screenshot from 2021-03-03 20-53-28](https://user-images.githubusercontent.com/35702189/109898915-01477980-7c63-11eb-83ff-21ed51f54b9e.png)

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
