### ISSUE TITLE
Being greylisted when "Send me test Ether"

### ISSUE THREAD

**Issue by yangy113** [Danielwu9226/community-currency-reframery#55]
![image](https://user-images.githubusercontent.com/70185196/110294753-3d942480-802b-11eb-932a-7cc2981e0060.png)

On `Step 2` of `smart-contract-usage.md`, I just misclicked `Send me test Ether` before entering my testnet account address. After I entered it again and clicked `Send me test Ether`, I just found I'm greylisted for like one day.

I think the risk of being greylisted in this step should be declared before the user do it.

**Comment by alishahimtiaz** [comment]
Closing as not repro bc test environment.
