### ISSUE TITLE
Negative values allowed in `mint` function

### ISSUE THREAD

**Issue by anthonylou** [Danielwu9226/community-currency-reframery#57]
Entering negative numbers into the `Amount` field of the `mint` function produces the following error: 

![Screenshot 2021-03-08 073814](https://user-images.githubusercontent.com/48287641/110322785-a48ceb80-7fe1-11eb-89a4-c415723ac9a0.png)

**Comment by alishahimtiaz** [comment]
This is intended behavior. Closing.
