### ISSUE TITLE
Error with /register as Defined in Instructions

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#6]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I followed the setup as instructed, but upon attempting to carry out the first POST request [here](https://github.com/Danielwu9226/community-currency-reframery/blob/master/API_DOCS.md), I received an internal error response.

![image](https://user-images.githubusercontent.com/17243618/109085307-6afddb80-76d7-11eb-9d3c-19bbe5096993.png)

And the command line error is as follows:
![image](https://user-images.githubusercontent.com/17243618/109085356-7ea94200-76d7-11eb-9dbc-dc3d1b4dbf44.png)

Based on the error, it seems the default setup for Django needs to be modified to work with your product. I'm not sure if this is just something missing in the README or not.

--Edit: I've solved the problem, and it's because you wrote ``127.0.0.1:8000/register`` in the instructions, while the correct command is ``127.0.0.1:8000/register/``.

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
