### ISSUE TITLE
Another Error with /register

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#7]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: After using the fix in my previous issue (#6), trying to create an account that already exists works properly, but trying to create a new account throws an Internal Server Error.

![image](https://user-images.githubusercontent.com/17243618/109085978-bd8bc780-76d8-11eb-9f7a-e6765605b51e.png)

And the command line output is:
![image](https://user-images.githubusercontent.com/17243618/109086084-ea3fdf00-76d8-11eb-9ef3-957dc46605e6.png)

After trying to create the new account again, it seems that it did actually go through previously, however, as I do get the proper error this time.

![image](https://user-images.githubusercontent.com/17243618/109086138-0774ad80-76d9-11eb-95ef-3e09181cac89.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
