### ISSUE TITLE
Error With /login/

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#8]
**Severity**: High

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: While attempting to log in with a faulty username and password works correctly (I'm not admitted and receive an unauthorized error), trying to login with the credentials I created previously using ``/register`` threw this error.

![image](https://user-images.githubusercontent.com/17243618/109086452-95e92f00-76d9-11eb-870b-463768bc509c.png)

And the command line output is:

![image](https://user-images.githubusercontent.com/17243618/109086422-8d90f400-76d9-11eb-8918-3d720d5d3cc2.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
