### ISSUE TITLE
Password Can be Changed to Same Password

### ISSUE THREAD

**Issue by Skeli789** [Danielwu9226/community-currency-reframery#9]
**Severity**: Low

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: This one is pretty self-explanatory.
My password is already ``123``, but I'm repeatedly able to change it to ``123``.

![image](https://user-images.githubusercontent.com/17243618/109086778-42c3ac00-76da-11eb-9759-80e9b8a8b0a2.png)

**Steps to Recreate**:
1. Follow the setup instructions and run the server.
2. Navigate to postman.com.
3. Try sending a request as indicated in the screenshot above.

**Comment by alishahimtiaz** [comment]
Fixed, thank you.
